// Famous typefaces, oldest first. `family` is the local font name tried for the plate title.
export type Font = { name: string; designer: string; year: string; family?: string };

export const FONTS: Font[] = [
  { name: "Jenson", designer: "Nicolas Jenson", year: "1470" },
  { name: "Garamond", designer: "Claude Garamond", year: "c. 1530", family: "Garamond" },
  { name: "Caslon", designer: "William Caslon", year: "1722", family: "Big Caslon" },
  { name: "Baskerville", designer: "John Baskerville", year: "1757", family: "Baskerville" },
  { name: "Didot", designer: "Firmin Didot", year: "1784", family: "Didot" },
  { name: "Bodoni", designer: "Giambattista Bodoni", year: "1798", family: "Bodoni 72" },
  { name: "Clarendon", designer: "Robert Besley", year: "1845" },
  { name: "Cheltenham", designer: "Bertram Goodhue", year: "1896" },
  { name: "Akzidenz-Grotesk", designer: "H. Berthold AG", year: "1898" },
  { name: "Copperplate Gothic", designer: "Frederic Goudy", year: "1901", family: "Copperplate" },
  { name: "Franklin Gothic", designer: "Morris Fuller Benton", year: "1902", family: "Franklin Gothic Medium" },
  { name: "News Gothic", designer: "Morris Fuller Benton", year: "1908" },
  { name: "Hobo", designer: "Morris Fuller Benton", year: "1910" },
  { name: "Plantin", designer: "Frank Hinman Pierpont", year: "1913" },
  { name: "Centaur", designer: "Bruce Rogers", year: "1914" },
  { name: "Goudy Old Style", designer: "Frederic Goudy", year: "1915" },
  { name: "Johnston", designer: "Edward Johnston", year: "1916" },
  { name: "Century Schoolbook", designer: "Morris Fuller Benton", year: "1919" },
  { name: "Cooper Black", designer: "Oswald Cooper", year: "1922" },
  { name: "Universal", designer: "Herbert Bayer", year: "1925" },
  { name: "Futura", designer: "Paul Renner", year: "1927", family: "Futura" },
  { name: "Kabel", designer: "Rudolf Koch", year: "1927" },
  { name: "Gill Sans", designer: "Eric Gill", year: "1928", family: "Gill Sans" },
  { name: "Perpetua", designer: "Eric Gill", year: "1929" },
  { name: "Bembo", designer: "Monotype", year: "1929" },
  { name: "DIN 1451", designer: "Deutsches Institut für Normung", year: "1931", family: "DIN Alternate" },
  { name: "Times New Roman", designer: "Stanley Morison & Victor Lardent", year: "1932", family: "Times New Roman" },
  { name: "Albertus", designer: "Berthold Wolpe", year: "1932" },
  { name: "Rockwell", designer: "Monotype", year: "1934", family: "Rockwell" },
  { name: "Peignot", designer: "A. M. Cassandre", year: "1937" },
  { name: "Trade Gothic", designer: "Jackson Burke", year: "1948" },
  { name: "Palatino", designer: "Hermann Zapf", year: "1949", family: "Palatino" },
  { name: "Microgramma", designer: "Aldo Novarese", year: "1952" },
  { name: "Mistral", designer: "Roger Excoffon", year: "1953" },
  { name: "Courier", designer: "Howard Kettler", year: "1955", family: "Courier New" },
  { name: "Letter Gothic", designer: "Roger Roberson", year: "1956" },
  { name: "Helvetica", designer: "Max Miedinger & Eduard Hoffmann", year: "1957", family: "Helvetica" },
  { name: "Univers", designer: "Adrian Frutiger", year: "1957" },
  { name: "Folio", designer: "Konrad Bauer & Walter Baum", year: "1957" },
  { name: "Optima", designer: "Hermann Zapf", year: "1958", family: "Optima" },
  { name: "Eurostile", designer: "Aldo Novarese", year: "1962" },
  { name: "Transport", designer: "Jock Kinneir & Margaret Calvert", year: "1963" },
  { name: "Impact", designer: "Geoffrey Lee", year: "1965", family: "Impact" },
  { name: "Snell Roundhand", designer: "Matthew Carter", year: "1965", family: "Snell Roundhand" },
  { name: "Rail Alphabet", designer: "Jock Kinneir & Margaret Calvert", year: "1965" },
  { name: "Sabon", designer: "Jan Tschichold", year: "1967" },
  { name: "Serifa", designer: "Adrian Frutiger", year: "1967" },
  { name: "Syntax", designer: "Hans Eduard Meier", year: "1968" },
  { name: "OCR-A", designer: "American Type Founders", year: "1968" },
  { name: "OCR-B", designer: "Adrian Frutiger", year: "1968" },
  { name: "Avant Garde", designer: "Herb Lubalin & Tom Carnase", year: "1970", family: "Avant Garde" },
  { name: "ITC Garamond", designer: "Tony Stan", year: "1975" },
  { name: "Frutiger", designer: "Adrian Frutiger", year: "1976" },
  { name: "Bell Centennial", designer: "Matthew Carter", year: "1978" },
  { name: "Galliard", designer: "Matthew Carter", year: "1978" },
  { name: "Arial", designer: "Robin Nicholas & Patricia Saunders", year: "1982", family: "Arial" },
  { name: "Papyrus", designer: "Chris Costello", year: "1982", family: "Papyrus" },
  { name: "Chicago", designer: "Susan Kare", year: "1984" },
  { name: "Geneva", designer: "Susan Kare", year: "1984", family: "Geneva" },
  { name: "Monaco", designer: "Susan Kare & Kris Holmes", year: "1984", family: "Monaco" },
  { name: "Lucida", designer: "Charles Bigelow & Kris Holmes", year: "1985", family: "Lucida Grande" },
  { name: "Avenir", designer: "Adrian Frutiger", year: "1988", family: "Avenir" },
  { name: "Trajan", designer: "Carol Twombly", year: "1989" },
  { name: "Minion", designer: "Robert Slimbach", year: "1990" },
  { name: "Scala", designer: "Martin Majoor", year: "1990" },
  { name: "Wingdings", designer: "Charles Bigelow & Kris Holmes", year: "1990" },
  { name: "Meta", designer: "Erik Spiekermann", year: "1991" },
  { name: "Myriad", designer: "Robert Slimbach & Carol Twombly", year: "1992" },
  { name: "Interstate", designer: "Tobias Frere-Jones", year: "1993" },
  { name: "Comic Sans", designer: "Vincent Connare", year: "1994", family: "Comic Sans MS" },
  { name: "Tahoma", designer: "Matthew Carter", year: "1994", family: "Tahoma" },
  { name: "Verdana", designer: "Matthew Carter", year: "1996", family: "Verdana" },
  { name: "Georgia", designer: "Matthew Carter", year: "1996", family: "Georgia" },
  { name: "Mrs Eaves", designer: "Zuzana Ličko", year: "1996" },
  { name: "Zapfino", designer: "Hermann Zapf", year: "1998", family: "Zapfino" },
  { name: "Gotham", designer: "Tobias Frere-Jones", year: "2000" },
  { name: "Akkurat", designer: "Laurenz Brunner", year: "2004" },
  { name: "Proxima Nova", designer: "Mark Simonson", year: "2005" },
  { name: "Calibri", designer: "Lucas de Groot", year: "2007", family: "Calibri" },
  { name: "Graphik", designer: "Christian Schwartz", year: "2009" },
  { name: "Tiempos", designer: "Kris Sowersby", year: "2010" },
  { name: "Roboto", designer: "Christian Robertson", year: "2011", family: "Roboto" },
  { name: "Open Sans", designer: "Steve Matteson", year: "2011", family: "Open Sans" },
  { name: "Circular", designer: "Laurenz Brunner", year: "2013" },
  { name: "San Francisco", designer: "Apple", year: "2015", family: "-apple-system" },
  { name: "Inter", designer: "Rasmus Andersson", year: "2017", family: "Inter" },
  { name: "IBM Plex", designer: "Mike Abbink", year: "2017", family: "IBM Plex Sans" },
  { name: "Söhne", designer: "Kris Sowersby", year: "2019" },
];
